[build]
builder = "nixpacks"

[deploy]
startCommand = "keystone postinstall && keystone start --with-migrations"
healthcheckPath = "/api/graphql"
healthcheckTimeout = 300
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "8080"